In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [ ]:
df =pd.read_csv("/content/Country-data.csv")
df

                 country  child_mort  exports  ...  life_expec  total_fer   gdpp
0            Afghanistan        90.2     10.0  ...        56.2       5.82    553
1                Albania        16.6     28.0  ...        76.3       1.65   4090
2                Algeria        27.3     38.4  ...        76.5       2.89   4460
3                 Angola       119.0     62.3  ...        60.1       6.16   3530
4    Antigua and Barbuda        10.3     45.5  ...        76.8       2.13  12200
..                   ...         ...      ...  ...         ...        ...    ...
162              Vanuatu        29.2     46.6  ...        63.0       3.50   2970
163            Venezuela        17.1     28.5  ...        75.4       2.47  13500
164              Vietnam        23.3     72.0  ...        73.1       1.95   1310
165                Yemen        56.3     30.0  ...        67.5       4.67   1310
166               Zambia        83.1     37.0  ...        52.0       5.40   1460

[167 rows x 10 columns]

In [ ]:
print("First 5 record")
print(df.head)

First 5 record
<bound method NDFrame.head of                  country  child_mort  exports  ...  life_expec  total_fer   gdpp
0            Afghanistan        90.2     10.0  ...        56.2       5.82    553
1                Albania        16.6     28.0  ...        76.3       1.65   4090
2                Algeria        27.3     38.4  ...        76.5       2.89   4460
3                 Angola       119.0     62.3  ...        60.1       6.16   3530
4    Antigua and Barbuda        10.3     45.5  ...        76.8       2.13  12200
..                   ...         ...      ...  ...         ...        ...    ...
162              Vanuatu        29.2     46.6  ...        63.0       3.50   2970
163            Venezuela        17.1     28.5  ...        75.4       2.47  13500
164              Vietnam        23.3     72.0  ...        73.1       1.95   1310
165                Yemen        56.3     30.0  ...        67.5       4.67   1310
166               Zambia        83.1     37.0  ...        52.0       5.40   1460

[167 rows x 10 columns]>

In [ ]:
X=df.drop("country",axis=1)
X

     child_mort  exports  health  ...  life_expec  total_fer   gdpp
0          90.2     10.0    7.58  ...        56.2       5.82    553
1          16.6     28.0    6.55  ...        76.3       1.65   4090
2          27.3     38.4    4.17  ...        76.5       2.89   4460
3         119.0     62.3    2.85  ...        60.1       6.16   3530
4          10.3     45.5    6.03  ...        76.8       2.13  12200
..          ...      ...     ...  ...         ...        ...    ...
162        29.2     46.6    5.25  ...        63.0       3.50   2970
163        17.1     28.5    4.91  ...        75.4       2.47  13500
164        23.3     72.0    6.84  ...        73.1       1.95   1310
165        56.3     30.0    5.18  ...        67.5       4.67   1310
166        83.1     37.0    5.89  ...        52.0       5.40   1460

[167 rows x 9 columns]

In [ ]:
scaler =StandardScaler()
X_scaled =scaler.fit_transform(X)
print(X_scaled[:5])

[[ 1.29153238 -1.13827979  0.27908825 -0.08245496 -0.8082454   0.15733622
  -1.61909203  1.90288227 -0.67917961]
 [-0.5389489  -0.47965843 -0.09701618  0.07083669 -0.3753689  -0.31234747
   0.64786643 -0.85997281 -0.48562324]
 [-0.27283273 -0.09912164 -0.96607302 -0.64176233 -0.22084447  0.78927429
   0.67042323 -0.0384044  -0.46537561]
 [ 2.00780766  0.77538117 -1.44807093 -0.16531531 -0.58504345  1.38705353
  -1.17923442  2.12815103 -0.51626829]
 [-0.69563412  0.1606679  -0.28689415  0.4975675   0.10173177 -0.60174853
   0.70425843 -0.54194633 -0.04181713]]

In [ ]:
X_scaled=pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns
)

In [ ]:
KMeans = KMeans(n_clusters=3, random_state=42, n_init=10)

In [ ]:
KMeans.fit(X_scaled)

KMeans(n_clusters=3, n_init=10, random_state=42)

In [ ]:
df['Cluster']=KMeans.labels_
print("\nCountries with Cluster:")
print(df[['country','Cluster']].head(15))

Countries with Cluster:
                country  Cluster
0           Afghanistan        1
1               Albania        2
2               Algeria        2
3                Angola        1
4   Antigua and Barbuda        2
5             Argentina        2
6               Armenia        2
7             Australia        0
8               Austria        0
9            Azerbaijan        2
10              Bahamas        2
11              Bahrain        0
12           Bangladesh        2
13             Barbados        2
14              Belarus        2

In [ ]:
print("\nNumber of countries int each cluster:")
print(df['Cluster'].value_counts().sort_index())

Number of countries int each cluster:
Cluster
0    36
1    47
2    84
Name: count, dtype: int64

In [ ]:
from sklearn.cluster import KMeans
model = KMeans(n_clusters=3)
model.fit(X_scaled)

KMeans(n_clusters=3)

In [ ]:
import pandas as pd
new_Sample = pd.DataFrame(
    [[10, 40, 7, 35, 30000, 5, 75, 2, 15000]],
    columns=X.columns
)


new_Sample_scaled = pd.DataFrame(
    scaler.transform(new_Sample),
    columns=X.columns
)


new_cluster = model.predict(new_Sample_scaled)

In [ ]:
print("\nNew Country Sample:")
print(new_Sample)

print("\nNew Country belongs to Cluster:",
      new_cluster[0])

New Country Sample:
   child_mort  exports  health  ...  life_expec  total_fer   gdpp
0          10       40       7  ...          75          2  15000

[1 rows x 9 columns]

New Country belongs to Cluster: 2